# Should the player see their own tag?
show-self: false

sneak:
  # Should we modify the opacity of the tag's background when the player shifts?
  enabled: true
  opacity: 70

defaults:
  # If not enabled then plugin simulates vanilla name tags
  enabled: true
  text:
    - "<white>%player_name%</white>"
    - "<blue>%player_ping%ms</blue>"
  background: black
  billboard: center
  shadow: true
  range: default
  gap: 0.2

groups:
  # e.g nametags.groups.vip
  vip:
    background: gray
  mvp:
    background: green
  staff:
    background: red

# Extra features
extra:
  # Should the name-tag be see-through if the player is glowing?
  glowing-feature: true