name: ${name}
main: ${main}
version: ${version}
author: ${author}
api-version: 1.17

depend:
  - packetevents

softdepend:
  - PlaceholderAPI
  - TAB
  - SkinsRestorer

commands:
  nametags-reload:
    description: Reload the config